# Generated by Django 5.1.3 on 2025-03-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumax_algo", "0004_rename_text_input_conversation_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="user_uploads/"),
        ),
    ]
