# Generated by Django 5.1.3 on 2025-03-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumax_algo", "0005_conversation_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
