# Generated by Django 5.1.3 on 2025-03-09 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumax_algo", "0006_alter_conversation_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="file",
        ),
        migrations.CreateModel(
            name="AttachedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("file", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumax_algo.conversation",
                    ),
                ),
            ],
        ),
    ]
