# Generated by Django 5.1.3 on 2025-03-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumax_algo", "0007_remove_conversation_file_attachedfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachedfile",
            name="title",
        ),
    ]
