# Generated by Django 5.1.3 on 2025-03-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumax_algo", "0008_remove_attachedfile_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachedfile",
            name="file",
        ),
        migrations.AddField(
            model_name="attachedfile",
            name="fileName",
            field=models.TextField(
                default="", help_text="The file path", max_length=500
            ),
        ),
    ]
