# Generated by Django 5.1.3 on 2025-03-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumax_algo", "0009_remove_attachedfile_file_attachedfile_filename"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachedfile",
            old_name="Conversation",
            new_name="conversation",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="prompt",
            field=models.TextField(
                default="", help_text="The user's prompt", max_length=1000
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="response",
            field=models.TextField(
                default="", help_text="The bot's response", max_length=1500
            ),
        ),
    ]
