# Generated by Django 5.1.3 on 2025-03-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumax_algo", "0010_rename_conversation_attachedfile_conversation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="prompt",
            field=models.TextField(
                default="", help_text="The user's prompt", max_length=3000
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="response",
            field=models.TextField(
                default="", help_text="The bot's response", max_length=3000
            ),
        ),
    ]
