# Generated by Django 5.2.6 on 2025-09-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumax_algo", "0012_alter_conversation_prompt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="prompt",
            field=models.TextField(
                default="", help_text="The user's prompt", max_length=8000
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="response",
            field=models.TextField(
                default="", help_text="The bot's response", max_length=20000
            ),
        ),
    ]
