# Generated by Django 5.2.6 on 2025-09-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumax_algo", "0013_alter_conversation_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="internal_analysis",
            field=models.TextField(
                default="", help_text="Internal analysis for the conversation"
            ),
        ),
    ]
