# Generated by Django 5.2.6 on 2025-09-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumax_algo", "0014_conversation_internal_analysis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachedfile",
            name="fileName",
        ),
        migrations.AddField(
            model_name="attachedfile",
            name="error_message",
            field=models.TextField(default="", help_text="Error message if any"),
        ),
        migrations.AddField(
            model_name="attachedfile",
            name="file_path",
            field=models.CharField(default="", help_text="File path", max_length=500),
        ),
        migrations.AddField(
            model_name="attachedfile",
            name="file_size",
            field=models.BigIntegerField(default=0, help_text="File size in bytes"),
        ),
        migrations.AddField(
            model_name="attachedfile",
            name="file_type",
            field=models.CharField(
                default="", help_text="File type/MIME type", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="attachedfile",
            name="original_filename",
            field=models.CharField(
                default="", help_text="Original file name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="attachedfile",
            name="processing_status",
            field=models.CharField(
                default="pending", help_text="Processing status", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="attachedfile",
            name="stored_filename",
            field=models.CharField(
                default="", help_text="Stored file name", max_length=255
            ),
        ),
    ]
