name: Pytest + CI/CD 

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
      - '*/*'
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY}}
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12.9"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set environment variables
      run: |
        echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
        echo "DJANGO_SETTINGS_MODULE=resumax_backend.settings" >> $GITHUB_ENV
        echo "PYTHONPATH=/home/runner/work/resumax/resumax/resumax_backend" >> $GITHUB_ENV
    - name: Run Django migrations
      working-directory: ./resumax_backend
      run: |
        python manage.py migrate --run-syncdb
    - name: Run Unit Tests with pytest framework and generate coverage report
      working-directory: ./resumax_backend
      run: |
        pytest --cov --cov-config=.coveragerc --cov-fail-under=70 --tb=short -v
    - name: Coveralls workflow
      working-directory: ./resumax_backend
      run: |
        coveralls --service=github
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY}}
    - name: Run Django Compilation CI/CD Tests
      run: |
        python ./resumax_backend/manage.py test
    - name: Black Code Formatter Command Run
      run: |
        python -m black ./
        # .github/workflows/django.yml
